### ISSUE TITLE
waar zijn de profielen?

### ISSUE THREAD

**Issue by WardJanssen** [trendygifts/trendygifts-preview#4]
De team members zijn nog niet zichtbaar op de site. Ik heb ze wel juist ingegeven

**Comment by VandeurenGlenn** [comment]
Did you check the homepage?

> The member-profile-cards are on the [homepage](http://trendygifts.github.io/trendygifts-preview/) in the team members section.
> The member list on the [admin backend](https://trendygifts.github.io/trendygifts-preview/#/admin/)
